FROM nginx
WORKDIR /usr/share/nginx/html/
COPY index.html .
ADD https://bestanimations.com/Site/Construction/under-construction-gif-6.gif under-construction-gif-6.gif
EXPOSE 80
ENV VARNAME=variablecontent
