FROM nginx
RUN curl https://bestanimations.com/Site/Construction/under-construction-gif-6.gif -o /usr/share/nginx/html/under-construction-gif-6.gif
RUN echo "<h1>PIESWEB</h1>" > /usr/share/nginx/html/index.html
RUN echo "<p>Pies are the best thing since sliced pies</p>" >> /usr/share/nginx/html/index.html
RUN echo "<img src=under-construction-gif-6.gif>" >> /usr/share/nginx/html/index.html


