apiVersion: v1
kind: Pod
metadata:
  name: bigpod
  labels:
    app: bigpod
spec:
  containers:
  - name: bigpod
    image: ghcr.io/home-assistant/home-assistant:2023.2.3
    ports:
    - containerPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bigpod 
  name: bigpod
spec:
  ports:
  - port: 80
    targetPort: 8123
  selector:
    app: bigpod
  type: LoadBalancer
