apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
