apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image:  reeceqa/python-frontend
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend 
  name: frontend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image:  reeceqa/python-backend
    ports:
    - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend 
  name: backend
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: backend
  type: ClusterIP
---
