all:
  vars:
          ansible_ssh_private_key_file: /home/ubuntu/feb23-anster.pem
          ansible_user: ubuntu
  children:
    test:
      hosts:
          172.31.41.169:
    production:
      hosts:
          172.31.40.243:
          172.31.43.195:
    London:
      hosts:
          172.31.43.195:
    Manchester:
      hosts:
          172.31.41.169:
          172.31.40.243:
