- name: Install nginx and some web files
  hosts: test
  tasks:
  - name: Install Nginx to the server
    apt:
      name: nginx
      state: present
      update_cache: true
  - name: Make sure the nginx is enabled
    systemd_service:
      name: nginx
      enabled: true
  - name: update the nginx config file
    copy:
      src: nginx.conf
      dest: /etc/nginx/
  - name: restart the ngixn service because we changed the config
    systemd_service:
      name: nginx
      state: restarted
  - name: copy the index web file
    copy:
      src: /home/ubuntu/FLA-Feb23/webapp/index.html
      dest: /var/www/html
  - name: copy the my-profile web file
    copy:
      src: /home/ubuntu/FLA-Feb23/webapp/my-profile.html
      dest: /var/www/html
  - name: copy the cool gif
    copy:
      src: /home/ubuntu/FLA-Feb23/webapp/under-construction-gif-6.gif
      dest: /var/www/html
